name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/setup-node@v2
      - run: npm i -g templay
      - run: templay
