name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v2
      - run: ls -la
      - run: npm run build
      - run: npm run templay
