name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test CLI
        uses: actions/setup-node@v2
      - name: Build binary
        run: yarn build
      - name: Create config file
        run: echo "templays:" > .templays.yml
      - name: Test help command
        run: ./bin/templay
      - name: Test list command
        run: ./bin/templay list
